#!/usr/bin/env ruby

require "fileutils"
require "gtt/downloader"

unless ENV['LABEL']
  puts <<USAGE
Usage: gtt-downloader LABEL="example"
USAGE
  exit 0
end

downloader   = Gtt::Downloader.new
label        = ENV['LABEL']
archive_path = downloader.download_label(label)
filename     = File.basename(archive_path).gsub(/ \(\d+\)(\.[^.]+)$/) { $1 }
FileUtils.mv(archive_path, File.join(FileUtils.pwd, filename))
